### PR TITLE
Attempting to get better at git....

### PR DESCRIPTION
**Pull request by rccreager**
Hi all,
Sorry for my git stupidity, I'm trying to learn the "right" way to place nice with others on git.

I want my "master" branch (in my remote "origin") to match the master of "upstream" (aka this repo). In this pull, my origin master should match upstream master (ignore the test file of course).

If you could accept this, then my "master" will be up-to-date with this one. And then when I'm ready to push changes from my development branch ("evaluation"), I'll merge the branch with my master branch, then submit a pull request to merge my master (containing my developed changes) with this master.

Once again, I know this is probably dumb. I appreciate your patience while I learn :)
Thanks,
Rachael
PS also sorry about the spam-y commit history. i didn't understand the difference between "origin master", "upstream master", and my local development branches.

### CODE REVIEW

**Comment by rccreager** [comment]
also sorry about the spam-y commit history. i didn't understand the difference between "origin master", "upstream master", and my local development branches.

**Comment by dguest** [comment]
Do we want to check in a 25 MB binary? I'm probably going to update it later, while I don't mind having a repository that grows to a few hundred MB I want to make sure this is really desired.

**Comment by mickypaganini** [comment]
I can help you out at the break :)

**Comment by rccreager** [comment]
shoot, i wasn't trying to check in the binary. if i "remove" it from my master branch (or ignore it?) i think that will fix the problem

**Comment by dguest** [comment]
Unfortunately removing a binary is hard. You have to make sure it was never checked in in the first place, which is a bit of history rewriting.

**Comment by rccreager** [comment]
i rolled my test.h5 file back to match the last commit. so now i *think* my master and upstream master are identical (and moved my test file to another directory)

**Comment by dguest** [comment]
We should talk about it when we have a break. Unfortunately with git you can still commit quite a lot of data without changing anything.

**Pull request closed without merging**
